### ISSUE TITLE
TypeError: get() got an unexpected keyword argument 'vars'

### ISSUE THREAD

**Issue by cis-muzahid** [cacois/python-configparser-examples#3]
`Traceback (most recent call last):
  File "/home/cis/projects/bitmessage/py/PyBitmessage/src/tests/test_config.py", line 22, in test_safeGetBoolean
    BMConfigParser().safeGetBoolean('nonexistent', 'nonexistent'),
  File "/home/cis/projects/bitmessage/py/PyBitmessage/pybitmessage/bmconfigparser.py", line 130, in safeGetBoolean
    return self.getboolean(section, field)
  File "/usr/lib/python3.7/configparser.py", line 828, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
TypeError: get() got an unexpected keyword argument 'vars'

======================================================================
ERROR: test_safeGetInt (src.tests.test_config.TestConfig)
safeGetInt retuns provided default for nonexistent option or 0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cis/projects/bitmessage/py/PyBitmessage/src/tests/test_config.py", line 34, in test_safeGetInt
    BMConfigParser().safeGetInt('nonexistent', 'nonexistent'), 0)
  File "/home/cis/projects/bitmessage/py/PyBitmessage/pybitmessage/bmconfigparser.py", line 148, in safeGetInt
    return self.getint(section, field)
  File "/usr/lib/python3.7/configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
TypeError: get() got an unexpected keyword argument 'vars'
`

I don't know what exactly the issue is

I am calling function getint like that

self.getint("section", "field")

**Comment by cacois** [comment]
You are using python 3, and the code was not python3 compatible. I just updated it to work with python3, please pull latest and try again.
